name: Price Data Collection

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir pandas==1.5.3
        pip install --no-cache-dir requests==2.28.2
        pip install --no-cache-dir beautifulsoup4==4.12.0
        pip install --no-cache-dir numpy==1.23.5
    
    - name: Run PV price scraper
      run: python scraper.py
      
    - name: Run EnergyTrend scraper
      run: python EnergyTrendScraper.py
      
    - name: Run Freightos rate collector
      env:
        FREIGHTOS_API_KEY: ${{ secrets.FREIGHTOS_API_KEY }}
      run: python freightos_client.py
    
    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/raw/*
        git add data/processed/*
        git add data/*.log
        git diff --staged --quiet || git commit -m "Update price data [automated]"
        git push https://${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
