name: PVInsights Price Scraper

on:
  schedule:
    - cron: '0 8 * * 1'  # Tous les lundis à 8h00 UTC
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Spécifions une version précise

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils python3-dev build-essential

    - name: Install basic Python packages
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel

    - name: Install project dependencies
      run: |
        pip install --no-cache-dir pandas==1.5.3
        pip install --no-cache-dir requests==2.28.2
        pip install --no-cache-dir beautifulsoup4==4.12.0
        pip install --no-cache-dir numpy==1.23.5
    
    - name: Run scraper
      run: python scraper.py
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/solar_prices.csv
        git commit -m "Update solar panel prices" || exit 0
        git push
